import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ErrorBoundary from "@/components/ErrorBoundary";
import ToastProvider from "@/utils/ToastProvider";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className="bg-slate-200">
        <Navbar />
        <ToastProvider />
        <ErrorBoundary>
        <div className="min-h-screen">{children}</div>
        </ErrorBoundary>
      </body>
    </html>
  );
}
